[aws]
disabled = true

[character]
format = ""
success_symbol = "(bold green) "
error_symbol = "(bold red) "

[directory]
format = "[$path]($style)[$read_only]($read_only_style) "
truncation_length = 4
truncate_to_repo = false
truncation_symbol = "â€¦/"

[git_status]
disabled = false

[hostname]
disabled = true

[package]
disabled = false

[time]
disabled = true
time_format = "%Y-%m-%d %H:%M"
utc_time_offset = "local"

[username]
style_root = "green bold"
format = "ğŸ˜ˆ [$user]($style) "
disabled = true
show_always = false

[git_branch]
symbol = "ğŸ’» "
truncation_length = 20
truncation_symbol = "â€¦"
style="bold purple"

[rust]
format = "via [âš™ï¸ $version](bold red)"

[python]
pyenv_version_name = true

[nodejs]
format = "via [ğŸ¤– $version](bold green) "